---
version: "3.6"

services:
  search_service:
    depends_on: [elastic]
    build: .
    ports:
      - 8080:8080
  elastic:
    image: blacktop/elasticsearch
    ports:
    - "9200:9200"
    - "9300:9300"
    